#!/usr/bin/env bash
#
# Build an Arch Linux pacman package (.pkg.tar.zst) from the unpacked
# Electron app produced by `task build`. Invoked via `task build:arch`.
#
# We generate the PKGBUILD on the fly instead of committing one because:
#   1. The `pkgver=` and `arch=` fields must track package.json + host arch.
#   2. The PKGBUILD's package() function references the absolute path of the
#      already-built app under out/, which differs per checkout.
#   3. There is no upstream source to download — makepkg's normal build()
#      step is skipped; package() just copies the pre-existing binaries
#      into $pkgdir. This is the same pattern electron-builder uses.
#
# Output: out/make/arch/<name>-<version>-1-<arch>.pkg.tar.zst, where <name>
# is the `name` field from package.json (so `zerx new` scaffolded projects
# get the right package name automatically).
#
# Install / uninstall after build:
#   sudo pacman -U  out/make/arch/<name>-*.pkg.tar.zst
#   sudo pacman -Rs <name>

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Map host machine -> (Node arch dir name, pacman arch field). Node arch is
# used because `task build` writes to out/relay-linux-<node-arch>/, matching
# the convention forced on us by Electron Packager and `process.arch`.
case "$(uname -m)" in
  x86_64)  NODE_ARCH=x64;   PKG_ARCH=x86_64 ;;
  aarch64) NODE_ARCH=arm64; PKG_ARCH=aarch64 ;;
  i686)    NODE_ARCH=ia32;  PKG_ARCH=i686 ;;
  *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
esac

# node, not jq/grep: node is already a dev dependency and parses JSON
# correctly without ad-hoc regex. NAME drives every project-name-derived
# path below so this script stays template-friendly — `zerx new` rewrites
# package.json's name but never has to touch this file.
NAME="$(node -p "require('${REPO_ROOT}/package.json').name")"
VERSION="$(node -p "require('${REPO_ROOT}/package.json').version")"

APP_DIR="${REPO_ROOT}/out/${NAME}-linux-${NODE_ARCH}"
if [[ ! -d "$APP_DIR" ]]; then
  echo "missing $APP_DIR; run 'task build' first" >&2
  exit 1
fi

BUILD_DIR="${REPO_ROOT}/out/make/arch"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# Heredoc with quoted EOF on the inner $-references (\$pkgdir, \$size) so
# they reach the PKGBUILD verbatim and are expanded by bash inside makepkg.
# Unquoted variables (${VERSION}, ${PKG_ARCH}, ${REPO_ROOT}, ${APP_DIR})
# are expanded here, freezing them into the file.
cat >"${BUILD_DIR}/PKGBUILD" <<EOF
# Auto-generated by scripts/make-arch.sh — do not edit by hand.
pkgname=${NAME}
pkgver=${VERSION}
pkgrel=1
pkgdesc="${NAME} desktop (Go backend + Electron renderer)"
arch=('${PKG_ARCH}')
url=""
license=('MIT')
# Electron's runtime deps on Linux. nss + libxss + libnotify cover the
# Chromium sandbox/notification surface; xdg-utils for xdg-open from links.
depends=('gtk3' 'nss' 'libxss' 'libnotify' 'xdg-utils')
# Skip makepkg's default post-processing: the Electron binaries are already
# stripped (-s -w on Go, Electron itself ships release builds), and trying
# to re-strip .so files inside Electron breaks ASAR integrity checks.
options=('!strip' '!debug' '!emptydirs')
source=()

package() {
  # 1. App tree under /opt/${NAME} (FHS-compliant location for third-party apps).
  install -dm755 "\$pkgdir/opt/${NAME}"
  cp -a "${APP_DIR}/." "\$pkgdir/opt/${NAME}/"

  # Normalise permissions. `cp -a` preserves source modes; if the developer
  # building the package has a restrictive umask (077 / 027), the top-level
  # /opt/<name> dir ends up owner-only (drwx------), and the desktop launcher
  # fails because /usr/bin/<name> -> /opt/<name>/<name> is unreachable for
  # non-root users. a+rX = world-read + execute on dirs (and on files that
  # already have x), which is the right minimum for an installed-system-wide
  # package.
  chmod -R a+rX "\$pkgdir/opt/${NAME}"

  # The Chromium SUID sandbox helper MUST be setuid root or Electron refuses
  # to start with "The SUID sandbox helper binary was found, but is not
  # configured correctly". Pacman preserves these bits on install. Run this
  # AFTER the chmod -R above, otherwise the recursive chmod clobbers the
  # setuid bit.
  chmod 4755 "\$pkgdir/opt/${NAME}/chrome-sandbox"

  # 2. /usr/bin shim so the .desktop file's Exec=<name> resolves on \$PATH.
  install -dm755 "\$pkgdir/usr/bin"
  ln -s /opt/${NAME}/${NAME} "\$pkgdir/usr/bin/${NAME}"

  # 3. Desktop entry + hicolor theme icons. File names (relay.desktop,
  # relay-<size>.png) intentionally stay as-is across scaffolded projects —
  # see the scaffold identity policy. The .desktop file's Exec= / Icon= /
  # StartupWMClass= fields are rewritten by the scaffold CLI to match \$NAME.
  install -Dm644 "${REPO_ROOT}/assets/relay.desktop" \\
    "\$pkgdir/usr/share/applications/${NAME}.desktop"

  for size in 16 32 48 64 128 256 512; do
    install -Dm644 "${REPO_ROOT}/assets/logo/png/relay-\${size}.png" \\
      "\$pkgdir/usr/share/icons/hicolor/\${size}x\${size}/apps/${NAME}.png"
  done
}
EOF

# makepkg refuses to run as root by default (good); --noconfirm avoids the
# "edit PKGBUILD?" prompt; --force overwrites any prior .pkg.tar.zst.
cd "$BUILD_DIR"
makepkg --force --noconfirm --clean

echo
echo "==> built: $(ls "${BUILD_DIR}/${NAME}"-*.pkg.tar.zst)"
echo "    install:  sudo pacman -U $(ls "${BUILD_DIR}/${NAME}"-*.pkg.tar.zst)"
